networkrail:
  target: dbt_networkrail

  outputs:
    dbt_networkrail:
      type: bigquery
      method: service-account
      project: dataengineer-bootcamp
      dataset: dbt_networkrail
      threads: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS_FOR_BIGQUERY') }}"
      location: asia-southeast1
